language: python
python:
   - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pelican content -s publishconf.py
# deployment to github pages repo
deploy:
  provider: pages
  local_dir: output
  repo: lessonsnlearnings/lessonsnlearnings.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master