language: python
python:
   - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pelican content
# deployment to github pages repo
deploy:
  provider: pages
  repo: $PAGES_REPO_URL
  local_dir: /output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master